### ISSUE TITLE
novej portal - novej loader

### ISSUE THREAD

**Issue by LiborD** [TOPefekt/BulkGate-issues#100]
nezobrazuje se novej loader...hodně často vidím ten starej kolečkovej
- viděl sem ho při sign inu, při změně psaní kampaně, tvorbě URL zkracovače, registraci
![image](https://user-images.githubusercontent.com/36260368/91294368-b0c5ff80-e799-11ea-803f-a1c1cb54d19d.png)

**Comment by MartinKreizl** [comment]
tady nebude
