### ISSUE TITLE
Adresář - úprava kontaktů

### ISSUE THREAD

**Issue by VeronikaRuliskova** [TOPefekt/BulkGate-issues#109]
Při úpravě kontaktů nejde uložit, nesvítí tlačítko 

![image](https://user-images.githubusercontent.com/40599364/104298864-c592fd80-54c4-11eb-887c-647b65f1b444.png)

**Comment by lukaspijak** [comment]
Za mě to normálně funguje, můžeš popsat jak to děláš, že to nejde?

**Comment by VeronikaRuliskova** [comment]
Nejde to ani Adéle, když upravím kontakt, uložím a chci ho upravit znovu, tak už mi nevyskočí ULOŽIT

U Adély to nejde ani napoprvé

**Comment by VeronikaRuliskova** [comment]
Tak mně už to jde, Adéle stále ne

**Comment by adelasulova** [comment]
Mně pořád nejde dát save
![image](https://user-images.githubusercontent.com/59650110/104313789-d8173200-54d8-11eb-9ffc-edda754fda3f.png)
![image](https://user-images.githubusercontent.com/59650110/104313828-e49b8a80-54d8-11eb-95c7-b0f19ca448a4.png)
