### ISSUE TITLE
Test Dev portalu

### ISSUE THREAD

**Issue by adelasulova** [TOPefekt/BulkGate-issues#113]
Platební system:
když zadáš částku v EUR, např. 10 eur propíše se vedle ta eurová částka v kreditech, což je špatně a nefunguje ani tečkování, zadání částky např. 10.2 eur
![image](https://user-images.githubusercontent.com/59650110/104304381-9764ec00-54cb-11eb-8769-2a0f0232d8a9.png)
![image](https://user-images.githubusercontent.com/59650110/104304739-0e9a8000-54cc-11eb-91a2-1c33e5ead9c9.png)

**Comment by lukaspijak** [comment]
vyřešeno
