### ISSUE TITLE
vyskakovaci dialogy

### ISSUE THREAD

**Issue by LiborD** [TOPefekt/BulkGate-issues#120]
uplne na prd...stoji to tam tak rok a nemuzu to ani odkrizkovat a zabira to uplne dulezity misto
![image](https://user-images.githubusercontent.com/36260368/104331842-d4db7080-54ef-11eb-9ccc-f3d08620a0ec.png)

**Comment by lukaspijak** [comment]
Ta proste po chvíli zmízí...
