### ISSUE TITLE
Nezobrazují se správně vlajky v adresáři

### ISSUE THREAD

**Issue by VeronikaRuliskova** [TOPefekt/BulkGate-issues#13]
![image](https://user-images.githubusercontent.com/40599364/72528547-9a52df80-386b-11ea-8cb6-d94158aa05ef.png)
Jak už to ale vyberu, tak je správně, ale s tímhle něco udělejte, není to hezký.

**Comment by lukaspijak** [comment]
Z inicializace tam jde iso kod z velkym pismenem.

![image](https://user-images.githubusercontent.com/2571714/72530051-d471b080-386e-11ea-929b-79805453b519.png)
