### ISSUE TITLE
Potvrzení odhlášení

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#181]
![image](https://user-images.githubusercontent.com/70203691/104564908-c6a26700-564b-11eb-8758-969d1c019e35.png)
?u odhlášení přidat konfirmační dialog "Opravdu se chcete odhlásit z aplikace?" nebo něco podobnýho...?

**Comment by lukaspijak** [comment]
Obecně jsem nikde moc neviděl, že by se někdo ptal, jestli chce odhlásit z aplikace.
