### ISSUE TITLE
Message page preview 500

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#205]
![image](https://user-images.githubusercontent.com/70203691/104594245-2b23ed00-5671-11eb-97a0-14d46718cb5b.png)
po prvním stlaceni tlacitka haže error, napodruhe už funguje, jo a ještě si musíš to okno shora roztahnout aby sis to přečetl, ale to už  jsem tam někde řešil....

**Comment by MartinKreizl** [comment]
z backendove strany to chce jeste promazat logiku pro preview v presenteru
