### ISSUE TITLE
Listovani mezi proměnnýma - tooltipy

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#206]
![image](https://user-images.githubusercontent.com/70203691/104595749-51e32300-5673-11eb-9b13-bbd65ff43d1d.png)
napoveda chybi

**Comment by MartinKreizl** [comment]
Tady by to chtelo integrovat nekam do layoutu, protoze z textarei bych ovladal i ostatni fieldy na strance. Tak jak je to ted by to nedavalo smysl. 
Navrhuju se nad tim poradne zamyslet a vymyslet to tak aby bylo jasny ze je nekde funkcionalita "prepinani preview promennych"
