### ISSUE TITLE
credits or EURO ?

### ISSUE THREAD

**Issue by lailaaksen** [TOPefekt/BulkGate-issues#22]
It is not clear of the costs 
it shows the EUro sign but it say credits
![image](https://user-images.githubusercontent.com/60003082/72614553-a3af7b00-3943-11ea-8ba2-be6ead4b64ba.png)

**Comment by lailaaksen** [comment]
also when I check into  price list it's impossible to know how many eruo = credits
so it's impossible to buy anything , because you have a campaign with XX amount in credit and when you want to buy you can only buy in Euro and you don't even know how many credit it is

**Comment by lukaspijak** [comment]
Icon changed

**Comment by lukaspijak** [comment]
![image](https://user-images.githubusercontent.com/2571714/72630012-bf218280-3951-11ea-8afc-8cb25e651da1.png)
