### ISSUE TITLE
Nástěnka - breakpointy @ front end

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#229]
![image](https://user-images.githubusercontent.com/70203691/104892240-3a0ce700-5972-11eb-8ca0-2bb59db9adf4.png)
![image](https://user-images.githubusercontent.com/70203691/104892472-85bf9080-5972-11eb-8076-cbf69103aa6c.png)
![image](https://user-images.githubusercontent.com/70203691/104892862-f797da00-5972-11eb-8c01-820de8a3db4d.png)

**Comment by MartinKreizl** [comment]
budou nove grafy
