### ISSUE TITLE
payment process only option is adding euro and not credit

### ISSUE THREAD

**Issue by lailaaksen** [TOPefekt/BulkGate-issues#23]
In the order process , we asked the option that custmer enter the amount in credit or Euro , but in the new interface we only can add euro and not credit
![image](https://user-images.githubusercontent.com/60003082/72615922-d60ea780-3946-11ea-8d4c-a9e8624ef815.png)

**Comment by lukaspijak** [comment]
We create new top up page on new system. It will be changed soon.
