### ISSUE TITLE
https://dev.bulkgate.com/top/up - velikost karet, nečitelné

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#256]
![image](https://user-images.githubusercontent.com/70203691/105009809-3d1fda00-5a3b-11eb-9916-ed653c74c4fb.png)

**Comment by lukaspijak** [comment]
Tady jsem nad tí přemýšlel a tady by to mělo být tak, že se postupně vysunují dle nabídky, takže za mě je to dobře takle.
