### ISSUE TITLE
Nástěnka - design

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#265]
![image](https://user-images.githubusercontent.com/70203691/105045147-da910300-5a67-11eb-9453-26ffdaf1b4e6.png)
stejná barva

**Comment by MartinKreizl** [comment]
Jdnotlive kanaly jako sms, viber apod.. jsou od sebe odliseny barvami. Takze si myslim ze tady to je nezadouci.
