### ISSUE TITLE
Osobní profil - scrollbar?

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#272]
![image](https://user-images.githubusercontent.com/70203691/105150217-c51de680-5b04-11eb-94de-e7d39ad2078a.png)
nějaká šipka nebo scroll bar, aby bylo zřejmé, že nabídka pokračuje doprava?

**Comment by MartinKreizl** [comment]
bude se implementovat novy uzivatelsky profil takze to ted nema cenu resit
