### ISSUE TITLE
Ceník - Systémové číslo

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#277]
![image](https://user-images.githubusercontent.com/70203691/105171459-8bf27000-5b1e-11eb-8ea9-19929338f059.png)
nějakej padding zprava?

**Comment by MartinKreizl** [comment]
Je potreba vyresit EmptyState komponentu. Tady tomu vadi width: 400px

**Comment by MartinKreizl** [comment]
Duplicate of #271
