### ISSUE TITLE
Osobní profil - nelze odstranit profilovou fotografii 

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#297]
![image](https://user-images.githubusercontent.com/70203691/105674617-143e8f80-5ee8-11eb-8a8e-e2fd3462530e.png)
nelze odstranit profilovou fotografii
- tak kecám, po refreshi zmizne, ale nevím jestli je to idealní chování

**Comment by lukaspijak** [comment]
zruseno aspon docasne
