### ISSUE TITLE
Osobní profil @media

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#298]
![image](https://user-images.githubusercontent.com/70203691/105679393-a9448700-5eee-11eb-9326-b107d5ad548e.png)
zvláštní chování, nejsou možnosti jak uložit, když dáš refresh tak vyskočí dialog "Smazat profilovou fotografii"
je to celé vol´aké čudné...

**Comment by lukaspijak** [comment]
zrušeno aspon docasne
