### ISSUE TITLE
osobní profil - tlačítko uložit v dialogu

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#314]
![image](https://user-images.githubusercontent.com/70203691/105725147-e3cb1580-5f28-11eb-9010-dba444b03d69.png)
![image](https://user-images.githubusercontent.com/70203691/105725405-3573a000-5f29-11eb-9175-e81cf90a0739.png)

nemělo by jít ukládat pokud se hodnota nezmění

**Comment by lukaspijak** [comment]
Ten profil se bude dělat nový, takže to nemá význam vylepšovat...
