### ISSUE TITLE
Price settings (list of countries)

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#317]
1. Seznam je posunutý vůči horní liště (je širší). Je potřeba to sladit. viz screenshot
![FireShot Capture 327 - Price Settings - BulkGate - dev bulkgate com](https://user-images.githubusercontent.com/39335258/105825772-428f9e00-5fc0-11eb-9161-54c5d42ba554.png)

2. Zobrazení procent ve sloupci "level (basic)/margin je zmatečný, je potřeba to lépe rozdělit, viz screenshot.
![FireShot Capture 330 - Price Settings - BulkGate - dev bulkgate com](https://user-images.githubusercontent.com/39335258/105825802-47ece880-5fc0-11eb-96f6-bd36c4f8605b.png)

3. Zobrazení procent ve sloupci "level (premium) / margin je zmatečný. Také potřeba rozdělit. Takto to působí, že je tam procentuelní rozsah, přitom jsou to dvě samostatná procenta a to 0% a druhá hodnota je minusová -13,04 

![FireShot Capture 335 - Price Settings - BulkGate - dev bulkgate com](https://user-images.githubusercontent.com/39335258/105825887-6357f380-5fc0-11eb-8e4e-800bfb486048.png)

4. Chybějící překlady

**Comment by MartinKreizl** [comment]
Jeste se musi vyresit to kdyz jsou datove hodnoty jine, ale po vykresleni na frontend jsou to vizualne stejna cisla viz:
![image](https://user-images.githubusercontent.com/4967862/106353049-058d1980-62e8-11eb-8549-4b5ff5810ab8.png)
![image](https://user-images.githubusercontent.com/4967862/106353057-19388000-62e8-11eb-9308-71c521e76823.png)

**Comment by MartinKreizl** [comment]
vyreseno zaokrouhlenim z backendu

> Jeste se musi vyresit to kdyz jsou datove hodnoty jine, ale po vykresleni na frontend jsou to vizualne stejna cisla viz:
> ![image](https://user-images.githubusercontent.com/4967862/106353049-058d1980-62e8-11eb-8549-4b5ff5810ab8.png)
> ![image](https://user-images.githubusercontent.com/4967862/106353057-19388000-62e8-11eb-9308-71c521e76823.png)

vyreseno v 4a748b3a zaokrouhlenim z backendu
