### ISSUE TITLE
Kampaň - nová kampaň - nelze změnit primární kanál

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#318]
![image](https://user-images.githubusercontent.com/70203691/105816412-9300fe80-5fb4-11eb-8845-ebe898b7f79a.png)
nejde změnit primární kanál.

**Comment by lukaspijak** [comment]
Pokud je jen jeden, což je tento případ, tak měnit nejde, protože nejsou jine moznosti.
