### ISSUE TITLE
Price settings

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#320]
název whitelabelu do seznamu např price settings - SunSMS

**Comment by MartinKreizl** [comment]
Udelal bych to tak, ze bych pri ulozeni vyvolal confirm tak jako je to ted. Pokud ale budu nastavovat jinej whiteLabel nez u kteryho je muj ucet, tak se v confirmu objevi checkbox s textm: "Jsem si vedem ze nastavuji cenu pro WhiteLabel XXX"
