### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#329]
![image](https://user-images.githubusercontent.com/70203691/105860887-61a52480-5fee-11eb-8bea-f8201aefa262.png)
pokud je API neaktivní, tak ho možná vyšednout, ať je to patrný, že to není aktivní , ta zelená tečka není moc vidět...

**Comment by MartinKreizl** [comment]
Misto tecky dat textovej status Enabled | Disabled ve stejne barve jako tecka. Bude jasnejsi k cemu se tecka vaze a co znamena
