### ISSUE TITLE
Ceník - nesedí počet zpráv

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#346]
![image](https://user-images.githubusercontent.com/70203691/106011479-c7f77900-60ba-11eb-9d74-054c69e0e918.png)
tady nám něco nesedí...

**Comment by kubaanec1** [comment]
jasný to je jako že máš o těch 13% větší bonus, ale není to teda moc pochopitelný...

**Comment by lukaspijak** [comment]
Proste to je nabídka, kterou dostaneš až od 5508 zpráv...
