### ISSUE TITLE
Ceník - nepřehledné

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#350]
![image](https://user-images.githubusercontent.com/70203691/106158443-086ef980-6184-11eb-927d-d8545a3f33ec.png)
nepřehledné, rozbalovací šipka by mohla mít jednotnej design, nahoře se rozbaluje pod "Počtem zpráv" dole bonusové nabídka se  se rozbalují pod cenou a sbalují....

**Comment by MartinKreizl** [comment]
Je to totiz jinej case. Nejde vzdycky vsechno udelat stejne. V tomto propade si myslim ze be to nebylo ve prospech veci
