### ISSUE TITLE
Změnová hláška - doba zobrazení 

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#377]
https://www.dropbox.com/s/cl0d7rh9q7wxnuv/hl%C3%A1%C5%A1ka%20prodleva.webm?dl=0
není to zobrazený moc dlouho? Někdy to brání kliknutí na tlačítko,, když je pod tím schovaný...

**Comment by lukaspijak** [comment]
za me dobry, zase musi byt videt co se deje
