### ISSUE TITLE
Abecední řazení státu při importu z excelu v kampani

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#38]
Při importu z excelu se v políčku country prefix státy, které mají počáteční písmeno s diakritikou, zobrazují až na konci. Hledal jsem stát Česko, které jsem očekával mezi písmeny C a D, ale našel jsem ho až úplně dole. Dost to mate,
Jazyk portálu jsem měl v češtině

**Comment by MartinKreizl** [comment]
Uz z backendu to jde nahovno.. je to snippet z raw dat primo v domu

![image](https://user-images.githubusercontent.com/4967862/73827039-21f29500-47ff-11ea-924a-35a186e95bbd.png)

**Comment by lukaspijak** [comment]
Ja jsem tam našel jednu chybu v lokalizačním řazení, ale stejně v kroku mezi 2 importu je to špatně.
