### ISSUE TITLE
[WhiteLabel] - nefunguje ukladani min a max payment

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#383]
![image](https://user-images.githubusercontent.com/70203691/107219648-a7f87b80-6a11-11eb-97f7-e8d78c190b90.png)
nějak nám to hapruje

**Comment by lukaspijak** [comment]
https://github.com/TOPefekt/BulkGate-issues/issues/387

**Comment by MartinKreizl** [comment]
Tato data posilam z frontendu:
![image](https://user-images.githubusercontent.com/4967862/107766633-084e2c80-6d34-11eb-833c-5b61dfeba4be.png)
a ze serveru mi prijdou v min a maxu nuly:
![image](https://user-images.githubusercontent.com/4967862/107766699-2320a100-6d34-11eb-88d0-807016d8af05.png)
