### ISSUE TITLE
Nejde nad importem v excelu zobrazit skutečný počet? Musí tam být 1000+ ?

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#39]
nahrál jsem import a vpravo mi to ukazuje nesmyslně 1000+, nemůže tam být prostě skutečná hodnota jako je v totalu 1766? přijde mi to mnohem lepší než takové nic neříkající zkreslování....
![obrazek](https://user-images.githubusercontent.com/39335258/73695380-4274ff00-46da-11ea-94eb-60b8265cd52b.png)

**Comment by MartinKreizl** [comment]
Zatim nechame zobrazovat cele cislo, ale kdyby s tim byl problem, tak to udelame jinak.
