### ISSUE TITLE
Upravit překlady pro testovací zprávu pro viber v summary, tam nemá slovo SMS co dělat.

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#41]
namísto SMS dát zpráva
![obrazek](https://user-images.githubusercontent.com/39335258/73697138-22473f00-46de-11ea-8cb8-94bda00c8ebe.png)

**Comment by MartinKreizl** [comment]
Preklad je spatnej, ale klic je za me v poradku. Opravit v databazi.

![image](https://user-images.githubusercontent.com/4967862/73849436-3b5d0680-482a-11ea-859c-1c91f5d578c9.png)
