### ISSUE TITLE
Kampaň - metody zadávání - Zadat čísla ručně

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#429]
![image](https://user-images.githubusercontent.com/70203691/107618628-2ba0ab00-6c52-11eb-95e2-99711389f1ef.png)
prosím přejmenovat na "Zadat čísla ručně" už jsem to tak požil v Helpdesku.

**Comment by MartinKreizl** [comment]
duplicate of #434
