### ISSUE TITLE
Proč mám zobrazené tlačítko change coverage, když mám aktivní jen jeden kanál....

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#43]
V tomto případě by se tlačítko nemělo zobrazovat.

![obrazek](https://user-images.githubusercontent.com/39335258/73746260-121e7680-4755-11ea-95e7-ccc8422359f1.png)

Edit coverage pak taky nedává žádný smysl, nejde tam nic měnit....

![obrazek](https://user-images.githubusercontent.com/39335258/73746306-2ebaae80-4755-11ea-8352-3337afff0eba.png)

**Comment by MartinKreizl** [comment]
Toto bylo jen kvuli reshoperu. Nyni odstraneno.
