### ISSUE TITLE
Kampaň - Improvement?

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#437]
![image](https://user-images.githubusercontent.com/70203691/108079517-32bf2300-706f-11eb-96c7-0cd4438be791.png)
zvolené položky Objednávkového formuláře bych asi přesunul dolů, přijde mim to logičtější, což?

**Comment by lukaspijak** [comment]
Tento princip máme stejně na jiných místech a osobně mi to více sedí nad tím...
