### ISSUE TITLE
Campaign workflow adding shortlink error

### ISSUE THREAD

**Issue by uneak** [TOPefekt/BulkGate-issues#450]
I encountered a problem when creating a new simple SMS sending campaign.
When creating / writing the message, I added a short link, - everything is ok
But when i try to send the campaign, i have this issue

![Capture d’écran 2021-02-17 à 10 07 11](https://user-images.githubusercontent.com/8837442/108223219-f8599280-710f-11eb-8b02-f5bc53dbaca8.png)

thank you

**Comment by lukaspijak** [comment]
I tried to make some optimizations and i hope that it will be ok.
