### ISSUE TITLE
Peněženky - Připojit peněženku vysvětlivky

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#458]
![image](https://user-images.githubusercontent.com/70203691/108684974-da1ada80-74f3-11eb-8cf6-1f747114527c.png)
to samý jako u Připojit peněženku, vysvětlivky, hvězdičky

**Comment by lukaspijak** [comment]
Hvezdicka je jako pro povinné pole, ale to bych nevysvetloval...
