### ISSUE TITLE
Ostrej BulkGate - Při změně státu v profilu mi to hodi hlasku a nevim, co to je za chybu

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#468]
Zmenil jsem v profilu country z Czechia na SLovakia a hodilo to chybu a nepoznam, co je za problem.
![FireShot Capture 344 - Personal profile - BulkGate - portal bulkgate com](https://user-images.githubusercontent.com/39335258/109152599-00e34600-776c-11eb-9801-e74322cc7112.png)

**Comment by MartinKreizl** [comment]
tay to bylo nejaky 500 server error, ale mohlo by se lepe prezentovat na frontendu v pripade dialogu. Protoze kdybys ten dialog zavrel tak zjistis ze je tam error state na obrazovce

**Comment by MartinKreizl** [comment]
na lokale uz to ted funguje, tak to asi jenom proverit

**Comment by lukaspijak** [comment]
Problém byl při ukončování session to hodilo 500, takže to proběhlo, jen Javascript četl chybu... Opraveno
