### ISSUE TITLE
ADRESÁŘ - v importu do adresáře mi nejde mazat staré importy

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#47]
Když kliknu v adresáři na smazat import, tak se nic nestane

![obrazek](https://user-images.githubusercontent.com/39335258/73790878-87b03400-47a1-11ea-8868-b1453bd779c0.png)

**Comment by LubomirKozak** [comment]
Zkoušel jsem provést nový import do adresáře a ani ten nelze smazat.

**Comment by MartinKreizl** [comment]
Pridal jsem jeste potvrzovani smazani souboru ve fazi vyberu sloupcu + po kliku na tlacitko zpet
