### ISSUE TITLE
Platební hladiny - překlad + duplikace názvu platební hladiny

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#475]
![image](https://user-images.githubusercontent.com/70203691/109160073-a18a3380-7775-11eb-8f87-f775095d47a6.png)
překladová fráze
nemá tam být Basic ?

**Comment by lukaspijak** [comment]
nemusí tam být basic, jde tam nastavit uz cokoliv v configuráku
