### ISSUE TITLE
Profily odesilatele

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#477]
![image](https://user-images.githubusercontent.com/70203691/109162946-11e68400-7779-11eb-9e5c-b812c6bad21b.png)
nevím kolik tam máme zákazníků ale nejde kliknout na Alandy

**Comment by lukaspijak** [comment]
to v pohodě, prostě to není nadefinovaný, takže tam nemuzeme posilat...
