### ISSUE TITLE
Ověření telefonního čísla -  nelze zadat předčíslí ručně - třeba +34

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#478]
![image](https://user-images.githubusercontent.com/70203691/109163354-8c170880-7779-11eb-9f54-8d164217a6a6.png)
toto mi dělalo i při registraci, dost nepříjemný, nelze smazat poslední číslo, už jsem to možná zmiňoval v nějakým starším issue

**Comment by lukaspijak** [comment]
https://github.com/TOPefekt/BulkGate-issues/issues/427
