### ISSUE TITLE
Nástěnka - Detail kampaně - default proměnná

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#479]
![image](https://user-images.githubusercontent.com/70203691/109176842-832d3380-7787-11eb-936e-1c6d6b7ceee2.png)
v detailu kampaně v textu zprávy se zobrazuje defaultní jméno místo real jména (získaného z proměnné) , ve zprávě to je cajk.

**Comment by lukaspijak** [comment]
Tam není žádné real name v té šabloně.
