### ISSUE TITLE
ADRESÁŘ - tlačítko vymazat ze skupiny se na full hd monitoru nevleze do horního menu

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#48]
viz screenshot

![obrazek](https://user-images.githubusercontent.com/39335258/73791232-33f21a80-47a2-11ea-9306-37a188111832.png)

**Comment by MartinKreizl** [comment]
> viz screenshot
> 
> ![obrazek](https://user-images.githubusercontent.com/39335258/73791232-33f21a80-47a2-11ea-9306-37a188111832.png)

Potrebne informace: 
- Prohlizec
- rozmery obrazovky.. nepovedlo se mi nasimulovat
