### ISSUE TITLE
Nastavení cen -  Bulkgate

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#485]
![image](https://user-images.githubusercontent.com/70203691/109300080-5f74f680-7836-11eb-9189-15901da8dd36.png)
tady se nám to nějak špatně řadí, ale jen u Chat-bot, SMS a Viber jsou seřazený normálně

**Comment by MartinKreizl** [comment]
tady to totiz jeste neni dodelany... nebudou tam staty ale kanaly (telegram, viber) ... takze proto
