### ISSUE TITLE
ADRESÁŘ - filtr na hledání telefonního čísla

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#49]
Mám v adresáři telefonní číslo +420603931624
Vyberu filtrovat podle telefonního čísla, zadám do filtru hodnotu 31624 a nic to nenajde.
Mělo by to najít všechna čísla, která obsahují 31624

**Comment by lukaspijak** [comment]
Jsou tam 2 filtry na telefonní číslo a na mobilní číslo. Dle testu to funguje dobře.
