### ISSUE TITLE
Osobní profil - Ověření telefonního čísla - tuning

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#492]
![image](https://user-images.githubusercontent.com/70203691/109496018-61d28d00-7a90-11eb-92c1-2e7e98a9442a.png)
"Ověřit telefonní číslo" bych dal, to zní líp ne?

**Comment by lukaspijak** [comment]
Tato obrazovka se bude předělávat, takže to nemá vyznam resit...
