### ISSUE TITLE
Sender type - chybí v nabídce - vlastní číslo

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#494]
![image](https://user-images.githubusercontent.com/70203691/109498478-ca6f3900-7a93-11eb-85f5-80a16e5e532b.png)
chybí typ odesilatele "vlastní číslo"

**Comment by lukaspijak** [comment]
Není chyba, pokud není žádné oveřené číslo, tak není zobrazen.

**Comment by kubaanec1** [comment]
![image](https://user-images.githubusercontent.com/70203691/109614824-69973d80-7b33-11eb-81d7-569058ca72a7.png)
Hele to je nějaký divný, v dashboardu to zobrazuje a v kampani ne.
V kampani to nezobrazuje ani Lubošovi, kterej má to číslo ověřený
