### ISSUE TITLE
SMS kampaň - chybí profil odesilatele v nabídce

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#495]
![image](https://user-images.githubusercontent.com/70203691/109498909-76188900-7a94-11eb-9356-ef1da0c1b6bf.png)
chybí profil "dsfds" v nabídce
![image](https://user-images.githubusercontent.com/70203691/109498981-8fb9d080-7a94-11eb-84f9-dc8a34b01a1f.png)

**Comment by lukaspijak** [comment]
To není chyba. Pokud profil nepodporuje konkrétní stát, který je zjistený z čísel, tak se nezobrazí.
