### ISSUE TITLE
WEB - ceník v cizích jazykových mutacích se zobrazuje v češtině a v CZK

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#55]
To je závažnej bug.

**Comment by MartinKreizl** [comment]
Jazyk na widget-API odchazi spravne. Preklady se ale nacitaji ceske (https://dev.bulkgate.com/translate/load/cs/SmsPrice)
![image](https://user-images.githubusercontent.com/4967862/74416043-cbabd480-4e44-11ea-9c70-8f61dd0ebe91.png)
