### ISSUE TITLE
Nová kampaň - chybí text v případě, že vyberu viber i SMS

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#59]
![obrazek](https://user-images.githubusercontent.com/39335258/74605721-e42d2080-50ca-11ea-9dff-040379eabfdc.png)

**Comment by LiborD** [comment]
https://trello.com/c/MgEarEqx/28-kampan pro tohle sem uz vytvoril issue, ktere bude delat marek
