### ISSUE TITLE
Nastavení datumu a času v summary - čas se nuluje, pokud se vrátím o krok zpět

### ISSUE THREAD

**Issue by LubomirKozak** [TOPefekt/BulkGate-issues#63]
v summary jsem zadal  čas odeslání na 15:20
![obrazek](https://user-images.githubusercontent.com/39335258/74606160-4a677280-50ce-11ea-8923-a2589bcd6a6f.png)

Vrátil jsem se o kro zpět do tvorby textu SMS zprávy a pak zpět do summary a čas se vynuloval:
![obrazek](https://user-images.githubusercontent.com/39335258/74606168-6834d780-50ce-11ea-937d-b843460d6cde.png)

čas by měl držet.

**Comment by MartinKreizl** [comment]
Bylo zpusobeno spatnym datovym typem v databazi
